ALTER TABLE mobile_users
  ADD COLUMN IF NOT EXISTS email      TEXT        NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status     VARCHAR(16) NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP;
