ALTER TABLE mobile_users
  ADD COLUMN IF NOT EXISTS vip_until TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  kind VARCHAR(16) NOT NULL DEFAULT 'vip',
  price_cents INTEGER NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  duration_days INTEGER NOT NULL DEFAULT 0,
  video_id INTEGER NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  user_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id),
  provider VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  amount_cents INTEGER NOT NULL,
  currency VARCHAR(8) NOT NULL,
  provider_order_id TEXT NOT NULL DEFAULT '',
  provider_payment_id TEXT NOT NULL DEFAULT '',
  checkout_url TEXT NOT NULL DEFAULT '',
  paid_at TIMESTAMP NULL,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_provider_order_id ON orders(provider, provider_order_id);

CREATE TABLE IF NOT EXISTS payment_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(16) NOT NULL,
  event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  order_no TEXT NOT NULL DEFAULT '',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  processed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(provider, event_id)
);

INSERT INTO products (code, name, description, kind, price_cents, currency, duration_days, status)
VALUES
  ('vip_monthly', 'VIP Monthly', '30 days VIP access', 'vip', 999, 'USD', 30, 'active'),
  ('vip_yearly', 'VIP Yearly', '365 days VIP access', 'vip', 9999, 'USD', 365, 'active')
ON CONFLICT (code) DO NOTHING;

INSERT INTO admin_menus(id, name, path, parent_id, type, permission) VALUES
  (27, 'payments',        '/payments', 0,  'menu',   ''),
  (28, 'payment:product', '',          27, 'button', 'payment:product'),
  (29, 'payment:order',   '',          27, 'button', 'payment:order'),
  (30, 'payment:refund',  '',          27, 'button', 'payment:refund')
ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  path       = EXCLUDED.path,
  parent_id  = EXCLUDED.parent_id,
  type       = EXCLUDED.type,
  permission = EXCLUDED.permission;

UPDATE admin_roles
SET menu_ids = menu_ids || '[27,28,29,30]'::jsonb
WHERE role_key = 'super_admin'
  AND NOT menu_ids @> '[27]'::jsonb;

SELECT setval(pg_get_serial_sequence('admin_menus','id'), COALESCE((SELECT MAX(id) FROM admin_menus), 1));
