CREATE TABLE IF NOT EXISTS video_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, video_id)
);

CREATE INDEX IF NOT EXISTS idx_video_favorites_user_id ON video_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_video_favorites_video_id ON video_favorites(video_id);

CREATE TABLE IF NOT EXISTS mobile_user_settings (
  user_id BIGINT PRIMARY KEY,
  auto_play BOOLEAN NOT NULL DEFAULT TRUE,
  wifi_only BOOLEAN NOT NULL DEFAULT FALSE,
  preferred_quality VARCHAR(24) NOT NULL DEFAULT 'auto',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
