ALTER TABLE video_transcode_tasks
  ADD COLUMN IF NOT EXISTS previous_status VARCHAR(32) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status_message TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attempt INT NOT NULL DEFAULT 0;
