ALTER TABLE videos
  ADD COLUMN IF NOT EXISTS audio_track_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtitle_track_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS media_tracks_scanned BOOLEAN NOT NULL DEFAULT FALSE;
