ALTER TABLE videos
  ADD COLUMN IF NOT EXISTS actors JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS directors JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS genres JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS region VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS release_year INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS language VARCHAR(128) NOT NULL DEFAULT '';
