-- User comments and ratings on videos. rating 0 means "comment only" (no star
-- rating); 1..5 is a star rating. The average rating shown on a video is
-- computed from rows with rating > 0.
CREATE TABLE IF NOT EXISTS video_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  rating SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_video_comments_video_id ON video_comments(video_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_video_comments_user_id ON video_comments(user_id);

-- Admin moderation menu + delete button.
INSERT INTO admin_menus(id, name, path, parent_id, type, permission, icon, sort_order) VALUES
  (35, '评论',           '/comments', 0,  'menu',   '',               'MessageSquare', 25),
  (36, 'comment:delete', '',          35, 'button', 'comment:delete', '',              0)
ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  path       = EXCLUDED.path,
  parent_id  = EXCLUDED.parent_id,
  type       = EXCLUDED.type,
  permission = EXCLUDED.permission,
  icon       = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

UPDATE admin_roles
SET menu_ids = menu_ids || '[35,36]'::jsonb
WHERE role_key = 'super_admin'
  AND NOT menu_ids @> '[35]'::jsonb;

SELECT setval(pg_get_serial_sequence('admin_menus','id'), COALESCE((SELECT MAX(id) FROM admin_menus), 1));
