-- Audit trail for admin mutations (POST/PUT/DELETE under /api/admin). Records who
-- did what, against which resource, and the resulting status, so destructive
-- actions (deletes, refunds, permission changes) leave a reviewable trace.
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT NOT NULL DEFAULT '',
  username   TEXT NOT NULL DEFAULT '',
  method     TEXT NOT NULL DEFAULT '',
  path       TEXT NOT NULL DEFAULT '',
  status     INT  NOT NULL DEFAULT 0,
  ip         TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_username ON audit_logs(username);

-- Read-only "审计日志" menu (super admin). No button permission: the GET list is
-- open to any authenticated admin, consistent with other read endpoints.
INSERT INTO admin_menus(id, name, path, parent_id, type, permission, icon, sort_order) VALUES
  (37, '审计日志', '/audit-logs', 0, 'menu', '', 'ScrollText', 26)
ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  path       = EXCLUDED.path,
  parent_id  = EXCLUDED.parent_id,
  type       = EXCLUDED.type,
  permission = EXCLUDED.permission,
  icon       = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

UPDATE admin_roles
SET menu_ids = menu_ids || '[37]'::jsonb
WHERE role_key = 'super_admin'
  AND NOT menu_ids @> '[37]'::jsonb;

SELECT setval(pg_get_serial_sequence('admin_menus','id'), COALESCE((SELECT MAX(id) FROM admin_menus), 1));
